VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_INSECURE = yes

QMK_SETTINGS = no
TAP_DANCE_ENABLE = no
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no

WPM_ENABLE = yes

I2C_DRIVER_REQUIRED = yes
SRC += screen_app.c tiny_mcu.c
